sudo: false

language: python

addons:
  apt:
    packages:
    - build-essential
    - libssl-dev
    - libncurses5-dev
    - unzip
    - subversion

before_script:
    - wget https://raw.githubusercontent.com/claudyus/owrt-package-test/master/owrt-pkgtest -P $HOME
    - chmod a+x $HOME/owrt-pkgtest

script:
    - mkdir files
    - cp -R tests/dummy_config/* files/
    - $HOME/owrt-pkgtest -r chaos_calmer -d meta openwisp-fw
